In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
print(a)

[1 2 3 4]


In [4]:
b =np.array([[5.0,6.0,7.0,8.0],[1.0,2.0,3.0,4.0]])

In [5]:
print(b)

[[5. 6. 7. 8.]
 [1. 2. 3. 4.]]


#### Muestra las dimensiones que tienen las matrices a y b

In [6]:
print("Número de Dimensiones: ", a.ndim)

Número de Dimensiones:  1


In [7]:
print("Número de Dimensiones: ", b.ndim)

Número de Dimensiones:  2


#### Muestra el datatype y el valor en bytes de los items en las matrices a y b

In [8]:
print("El tipo es dato es",a.dtype, "para la matríz a con un tamaño de", a.itemsize, "bytes")

El tipo es dato es int64 para la matríz a con un tamaño de 8 bytes


In [9]:
print("El tipo es dato es",b.dtype, "para la matríz b con un tamaño de", b.itemsize, "bytes")

El tipo es dato es float64 para la matríz b con un tamaño de 8 bytes


#### Muestra las formas para las matrices a y b

In [10]:
a.shape

(4,)

In [11]:
b.shape

(2, 4)

##### Asigna un datatype fijo

In [12]:
c = np.array([1,2,3,4,5], dtype='int32')

In [13]:
c.dtype

dtype('int32')

#### Obtiene el valor total de un array

In [14]:
print("Tamaño total del array c es:", c.size * c.itemsize, "bytes")

Tamaño total del array c es: 20 bytes


In [15]:
c.nbytes

20

#### Obtiene un elemento de un array [f, c]

In [16]:
d = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
d.shape

(2, 7)

In [18]:
d[0, 1]   # Extrae el número de la fila cero columna uno

2

In [19]:
d[1,5]    # Extrae el número de la fila uno columna cinco

13

In [20]:
d[0,-3]    # Extrae el número de la fila cero columna -3 (se empiza del final con -1)

5

#### Obtiener una fila o columna en un array [f, c]

In [21]:
d[0, :]   # Toma todos los elementos de la fila cero

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
d[:, 4]   # Toma todos los elementos de la columna 4

array([ 5, 12])

In [23]:
d[0, 1:6:2]   # Toma los elemento de la fila cero desde la columna 1 a la 6, de 2 en 2

array([2, 4, 6])

In [24]:
d[0, 1:-1:2]

array([2, 4, 6])

In [25]:
d[0, 0:-2:1]

array([1, 2, 3, 4, 5])

#### Remplaza elementos de un array [f, c]

In [26]:
d[0,3] = 22
print(d)

[[ 1  2  3 22  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [27]:
d[0, :] = 1
d[1, :] = 44
print(d)

[[ 1  1  1  1  1  1  1]
 [44 44 44 44 44 44 44]]


In [28]:
d[:, 3] = 0
print(d)

[[ 1  1  1  0  1  1  1]
 [44 44 44  0 44 44 44]]


In [29]:
d[:, 2] = [8, 22]
print(d)

[[ 1  1  8  0  1  1  1]
 [44 44 22  0 44 44 44]]


#### 3 Dimensiones

In [30]:
e = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(e)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Obtener y cambiar elementos [d, f, c]

In [31]:
e[1, 0, 1]

6

In [32]:
e[:, 0, :]

array([[1, 2],
       [5, 6]])

In [33]:
e[:, :, 0]

array([[1, 3],
       [5, 7]])

In [34]:
e[:, 1, :] = [[1, 1],[9, 9]]
print(e)

[[[1 2]
  [1 1]]

 [[5 6]
  [9 9]]]


#### Tipos de Arrays

In [35]:
#Solo ceros
np.zeros(4)

array([0., 0., 0., 0.])

In [36]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.zeros((2,3,4,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [38]:
#Solo unos
np.ones((2, 2, 2), dtype='float32')

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

In [39]:
#Cualquier número
np.full((3,3), 99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [40]:
#Cambia los valores de una matriz
np.full_like(a, 10)

array([10, 10, 10, 10])

In [41]:
#Matriz con valores decimales aleatorios
np.random.rand(4, 3)

array([[0.39976399, 0.51577735, 0.19142024],
       [0.66998347, 0.40824198, 0.89638536],
       [0.55567927, 0.81589502, 0.94483562],
       [0.63726793, 0.0787668 , 0.14802987]])

In [42]:
np.random.random_sample(e.shape)

array([[[0.44937705, 0.54351272],
        [0.51080341, 0.15225928]],

       [[0.15199441, 0.98626894],
        [0.11217539, 0.10322801]]])

In [43]:
#Crea una matriz con valores entre cero y cinco
np.random.randint(5, size=(4,4))

array([[1, 4, 0, 0],
       [0, 3, 2, 2],
       [0, 2, 0, 0],
       [1, 0, 4, 3]])

In [44]:
np.random.randint(-10, 10, size=(5,5))

array([[-3, -3,  0,  7, -8],
       [ 6,  0, -9,  6,  7],
       [ 7,  3,  2, -6, -2],
       [-1, -1,  1, -3,  5],
       [ 4,  9, -9, -5,  4]])

In [45]:
#Matriz identidad
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
a0 = np.array([1,2,3])
a1 = np.repeat(a0, 3)
print(a1)

[1 1 1 2 2 2 3 3 3]


In [47]:
a0 = np.array([[1,2,3]])
a1 = np.repeat(a0, 3, axis=0)
print(a1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#### Operaciones avanzadas sobre una matriz

In [48]:
matriz1 = np.ones((5,5))
print(matriz1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [49]:
matriz2 = np.zeros((3,3))
matriz2[1,1] = 8
print(matriz2)

[[0. 0. 0.]
 [0. 8. 0.]
 [0. 0. 0.]]


In [50]:
matriz1[1:4,1:4] = matriz2   #Mueve la matriz 1 a la posición que esta entre la fila y columna 1 y fila y columna 3
print(matriz1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 8. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Copiar

In [51]:
f = np.array([1,2,3])
g = np.array([0,0,0])
g = f
g

array([1, 2, 3])

In [52]:
#Se cambia el valor en ambos arrays al usar únicamente el signo '=' para realizar copias
g[0] = 100
print(f)

[100   2   3]


In [53]:
#Se crea una copia independiente
f = np.array([1,2,3])
g = np.array([0,0,0])
g = f.copy()
g
g[0] = 100
print(f)

[1 2 3]


#### Operaciones Matemáticas

In [54]:
w = np.array([1,2,3,4])
print(w)

[1 2 3 4]


In [55]:
#Suma
w + 5

array([6, 7, 8, 9])

In [56]:
#Resta
w - 2

array([-1,  0,  1,  2])

In [57]:
#Multiplicación
w * 3

array([ 3,  6,  9, 12])

In [58]:
#División
w / 2

array([0.5, 1. , 1.5, 2. ])

In [59]:
#Suma matricial
x = np.array([1,0,1,0])
w + x

array([2, 2, 4, 4])

In [60]:
#Potencia
w ** 3

array([ 1,  8, 27, 64])

In [61]:
#Seno
np.sin(w)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [62]:
#Coseno
np.cos(w)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [63]:
#Exponencial
np.exp(w)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [64]:
#Logaritmo
np.log(w)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [65]:
#Raíz
np.sqrt(w)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [66]:
#Valor absoluto
np.abs(w)

array([1, 2, 3, 4])

In [67]:
#Arcotangente
np.arctan(w)

array([0.78539816, 1.10714872, 1.24904577, 1.32581766])

#### Algebra lineal

In [68]:
x = np.ones((2,3))
print(x)

y = np.full((3,2),2)
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [69]:
#Multiplicación matricial
np.matmul(x,y)

array([[6., 6.],
       [6., 6.]])

In [70]:
#Muestra el determinante de una matriz identidad
z = np.identity(3)
np.linalg.det(z)

1.0

In [71]:
z = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(z)
# Calcular la traza de la matriz
traza = np.trace(z)
print("Traza de la matriz:", traza)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Traza de la matriz: 15


In [72]:
# Calcular la descomposición de valores singulares (Singular Value Decomposition - SVD)
u, s, vh = np.linalg.svd(z)
print("Matriz U (izquierda):")
print(u)
print("Valores singulares (diagonal):")
print(s)
print("Matriz V^T (derecha):")
print(vh)

Matriz U (izquierda):
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Valores singulares (diagonal):
[1.68481034e+01 1.06836951e+00 4.41842475e-16]
Matriz V^T (derecha):
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [73]:
# Calcular los eigenvalores y eigenvectores de la matriz
eigenvalores, eigenvectores = np.linalg.eig(z)
print("Eigenvalores:")
print(eigenvalores)
print("Eigenvectores:")
print(eigenvectores)

Eigenvalores:
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigenvectores:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [74]:
# Calcular la norma de Frobenius de la matriz
norma = np.linalg.norm(z, ord='fro')
print("Norma de Frobenius de la matriz:", norma)

Norma de Frobenius de la matriz: 16.881943016134134


In [75]:
# Calcular la inversa de la matriz
z = np.identity(3)
inversa = np.linalg.inv(z)
print("Inversa de la matriz:")
print(inversa)

Inversa de la matriz:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Estadística

In [76]:
k = np.array([[1,2,3],[4,5,6]])
k

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.min(k)

1

In [78]:
np.max(k)

6

In [79]:
np.sum(k)

21

#### Redimensionar Arrays

In [80]:
l = np.array([[1,2,3,4],[5,6,7,8]])
print(l)
print("Su dimensión es:", l.shape)

[[1 2 3 4]
 [5 6 7 8]]
Su dimensión es: (2, 4)


In [81]:
m = l.reshape((8,1))
print(m)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [82]:
m = l.reshape((4,2))
print(m)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [83]:
m = l.reshape((2,2,2))
print(m)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [84]:
#Apilar vectores vecticalmente
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np .vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
np .vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [86]:
#Apilar vectores horizontalmente
h1 = np.ones((2,4))
h2 = np.zeros((2,8))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [87]:
np.hstack((h1,h2,h1))

array([[1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.]])

#### Funciones extra

In [88]:
#Importa una matriz desde un archivo .txt
matriz3 = np.genfromtxt('test.txt', delimiter=',')
print(matriz3)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]]


In [89]:
#Crea un archivo con números aleatorios
matriz4 = np.random.rand(5, 12)
np.savetxt('numeros_aleatorios.csv', matriz4, delimiter=',', fmt='%.6f')
print(matriz4)

[[0.23539243 0.71076504 0.39085441 0.05514585 0.69808883 0.33210425
  0.36284061 0.15857717 0.05796109 0.83111992 0.77399438 0.94271055]
 [0.7590061  0.32769907 0.09366086 0.93034119 0.19567799 0.22261681
  0.30226468 0.18332506 0.70870156 0.54042581 0.2770182  0.23119814]
 [0.62589552 0.64257122 0.67061184 0.34430922 0.31451773 0.89881409
  0.74293399 0.96798703 0.82069408 0.97390817 0.91115251 0.01293012]
 [0.1982794  0.93374315 0.34659432 0.36854902 0.67388766 0.34227892
  0.57024759 0.22232402 0.48332564 0.52681836 0.82111973 0.42140554]
 [0.05688097 0.36829504 0.26259914 0.49192868 0.24962374 0.92715503
  0.97509359 0.02288412 0.13206944 0.17546118 0.77242486 0.35178413]]


#### Indexado Avanzado

In [90]:
matriz5 = matriz3.astype('int32')
print(matriz5)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [91]:
matriz5 > 15

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [92]:
matriz5[matriz5 < 8]

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int32)

In [93]:
#Seleccionar por posición
matriz6 = np.array([1,2,3,4,5,6,7,8,9])
matriz6[[0,2,5,8]]

array([1, 3, 6, 9])

In [94]:
np.any(matriz5 > 20)   # Devuelve un valor booleano verdadero en caso de haber algún valor mayor a 20

True

In [95]:
#Muestra si en el eje 0 (columnas) existen valores mayores a 20
print(matriz5)
np.any(matriz5 > 20, axis=0)   # Muestra un verdadero en caso de que exista un valor mayor a 20, contando columna a columna

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [96]:
#Muestra si en el eje 1 (filas) existen valores mayores a 20
np.any(matriz5 > 20, axis=1)

array([False, False,  True])

In [97]:
#Muestra si en el eje 1 todos los valores mayores a 20
np.all(matriz5 > 20, axis=1)

array([False, False, False])

In [98]:
#Muestra si existen valores mayores a 11 y menores a 18
((matriz5 > 11) & (matriz5 < 18))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False,  True,  True,  True,  True,  True,  True, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [99]:
#El proceso inverso
(~((matriz5 > 11) & (matriz5 < 18)))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False, False, False, False, False, False,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

#### Ejercicio

In [100]:
matriz6 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(matriz6)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [101]:
matriz6[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [102]:
matriz6[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [103]:
matriz6[[0,3,4], 3:]

array([[ 4,  5],
       [19, 20],
       [24, 25]])